### ISSUE TITLE
Send amounts with the nightscout uploader

### ISSUE THREAD

**Issue by ACWalker** [j-kaltes/Juggluco#106]
First of all, thank you for this app, it has really improved a lot of things for me!

I was wondering whether it is currently possible, or could be made possible to send treatment amounts via the nightscout uploader. 

For example, I would like to add my fast acting insulin treatment scanned from my EchoPen on juggluco, and then be able to send that to my nightscout server via the uploader in Juggluco. As raised in https://github.com/j-kaltes/Juggluco/issues/95 it seems like it is possible to do something similar with the inbuilt nightscout server, with the "give amounts" option. Is it possible to do this in the uploader?

**Comment by j-kaltes** [comment]
No, it isn’t implemented in the uploader to Nightscout. As you said already, you can use the build in [Nightscout web server](https://www.juggluco.nl/Juggluco/webserver.html) for that. You can also run that web server on a computer https://www.juggluco.nl/Juggluco/cmdline/index.html
The amounts can also be sent to Libreview.
EDIT:
For what apps do you need the insulin in the Nightscout server? 
I contemplate patching AAPS so that it can make use of the Nightscout web server in Juggluco. That way AAPS wouldn’t be dependent on a potentially unreliable and dangerous internet connection anymore.

**Comment by ACWalker** [comment]
Thanks for your response. I would use the built in web server, but I like to use the actual UI of nightscout as well, so unfortunately would have to build something on top of the APIs exposed.

I currently use my Nightscout server in the cloud as an archive and as a means to see my sugars from my PC and share with others. Unfortunately I haven't got access to any pumps yets, so i'm on MDI.  The reason i'd like to sync insulin is to be able to use the nightscout bolus calculator functionality, add my insulin data to my archive and see the insulin on board lines displayed on nightscout to help with correction/low decisions.

I had that all working when I was using xDrip, but the problems with the slow pollng or double smoothing of libre data in xDrip just drove me nuts.

**Comment by ACWalker** [comment]
@j-kaltes just tried the new update and it works a treat! Thanks again for all your hard work, it's definitely helped make things easier for me
