### ISSUE TITLE
'LibAscon' file directory does not exist

### ISSUE THREAD

**Issue by q601180252** [j-kaltes/Juggluco#2]
CMake Error at CMakeLists.txt:40 (add_library):
  Cannot find source file:

    /juggluco/app/src/main/cpp/LibAscon/src/ascon_permutations.c

**Comment by j-kaltes** [comment]
Git refused to add LibAscon because it contained its own .git directory. Now it is included. 
The following files are also missing, but can be found by unzipping a recent Juggluco apk.  If you want to include arm64-v8a only, you can uncomment  _ndk { abiFilters  'arm64-v8a' }_ in Common/build.gradle

./Common/src/main/jniLibs/x86_64/libcalibrat2.so
./Common/src/main/jniLibs/x86_64/libcalibrate.so

./Common/src/main/jniLibs/armeabi-v7a/libcalibrat2.so
./Common/src/main/jniLibs/armeabi-v7a/libcalibrate.so

./Common/src/main/jniLibs/x86/libcalibrat2.so
./Common/src/main/jniLibs/x86/libcalibrate.so

./Common/src/main/jniLibs/arm64-v8a/libcalibrat2.so
./Common/src/main/jniLibs/arm64-v8a/libcalibrate.so


./Common/src/libre3/jniLibs/x86_64/libcrl_dp.so
./Common/src/libre3/jniLibs/x86_64/liblibre3extension.so
./Common/src/libre3/jniLibs/x86_64/libinit.so

./Common/src/libre3/jniLibs/armeabi-v7a/libcrl_dp.so
./Common/src/libre3/jniLibs/armeabi-v7a/liblibre3extension.so
./Common/src/libre3/jniLibs/armeabi-v7a/libinit.so

./Common/src/libre3/jniLibs/x86/libcrl_dp.so
./Common/src/libre3/jniLibs/x86/liblibre3extension.so
./Common/src/libre3/jniLibs/x86/libinit.so

./Common/src/libre3/jniLibs/arm64-v8a/libcrl_dp.so
./Common/src/libre3/jniLibs/arm64-v8a/liblibre3extension.so
./Common/src/libre3/jniLibs/arm64-v8a/libinit.so
