### ISSUE TITLE
Status bar overlaps settings window and makes units unclickable

### ISSUE THREAD

**Issue by rinukkusu** [j-kaltes/Juggluco#205]
I'm just installing the Juggluco App on my Xiaomi Poco and the unit selection renders under the status bar. Even with the "notch" turned off, where apps should render below the status bar and not "edge to edge", it still renders under the status bar.

![Screenshot_2024-09-20-20-02-38-135_tk glucodata](https://github.com/user-attachments/assets/20fca6fa-ab7d-4e2e-b50f-57a339a0ba8a)

Any ideas on how to get me set up? Can I maybe edit the settings manually somewhere in a file or database?

Thanks and BR

**Comment by j-kaltes** [comment]
You should be able to scroll the screen down, so that the unit is below the status bar:
![one](https://github.com/user-attachments/assets/d45aab6c-b1b7-45d9-bb66-15e72eb71c9b)
Scroll->
![two](https://github.com/user-attachments/assets/b94c292c-2023-4c75-ab17-c7e92d388af2)

Do you use Juggluco 8.1.7?

By the way, why did you disable "_Sensor über Bluetooth_"? Do you have a WearOS watch?

**Comment by rinukkusu** [comment]
Hi, this was the default when I installed the app afaik, literally just set it up. I was not able to pull it down from there, but after a few restarts and forth and backs, the app suddenly rendered below the status bar. So maybe this was just a MIUI quirk. No idea.

Thank you for looking into it, though!
