### ISSUE TITLE
Sensor unusable if phone battery dies

### ISSUE THREAD

**Issue by KiSa04** [j-kaltes/Juggluco#229]
1. Sensor is receiving values via bluetooth using juggluco
2. The phone that is connected with the sensor is turned off due to no battery
3. Try to use another phone (using the same juggluco version) to read the sensor
4. Sensor becomes unusable until it ends

more details:
The sensor can still be read via NFC, but on bluetooth an error status of "255" is displayed constantly until it is replaced. 
It stops working with both juggluco and LibreLink app.
I've had this happen about 4 times in the last weeks, as my phone's battery became unstable and it shuts down unexpectedly, every time it shut down while connected to the sensor, bluetooth became unusable and i had to replace the sensor 
If the sensor is replaced, bluetooth works fine on the new one

attempts:
Terminating and Forgetting the sensor doesn't fix it.
Re-installing juggluco doesn't fix this (which makes sense, as librelink also stops working)

ps:
this could, of course, be a problem with the sensors, but the timings i've been having are quite weird. E.g. the sensor that just stopped working was 4 days old and working fine so far. The other sensors were a bit older, but working fine until the phone shutdown

**Comment by j-kaltes** [comment]
You are using Libre 2 sensors?
I have experienced this a lot of times with Libre 2 sensor, and never the sensor becomes unusable. When the sensor is scanned with another phone, it sometimes takes a long time before Juggluco regains the connection with the sensor. But it is possible when you first wait for _streaming not enabled_ to emerge in left menu->Sensor and then scan the sensor.
Scanning the sensor is essential for regaining Bluetooth contact with the sensor.
I myself don't experience status=255 connection errors. Other users did mention status=255 errors and that it was kind of hopeless, but nobody mentioned a relation with the phone battery dying. I also don't see why that could matter. For the sensor it is not different from getting out of reach. Scanning the sensor with another phone matters: you need to scan the sensor after Juggluco comes to know that it's authentication information doesn't work anymore.

It is possible that because the phone dies, another device gets a connection with the sensor and because of that reconnecting fails.

**Comment by KiSa04** [comment]
So, the sensor came back to life after 4 days on status=255 error
To test the battery theory (on a new sensor), i've tried to replicate the described scenario two more times and it didn't come up with error 255, so it's clear that it was only a coincidence
