### ISSUE TITLE
Sibionics Missing 

### ISSUE THREAD

**Issue by postn** [j-kaltes/Juggluco#240]
Hello. I am getting my first sibionics CGM next week and wanted to activate it with Juggluco, as per other GitHub topics and changelog I should see Sibionics in the left menu but I see photo and not sibionics. 

Is photo what I need to use? Also I assume I can activate the CGM without the official app I suppose. 

Thanks for the app and happy to share screenshots if needed.

**Comment by j-kaltes** [comment]
What do you want to do with the Sibionics menu item?

Do you have Chinese market Sibionics sensors?

**Comment by postn** [comment]
I have ordered one from AliExpress which by the way the pics are showing probably is Chinese version (will know for sure next week). 

Is my understanding right that if it's Chinese version then I can use juggluco if it's not then I can't use juggluco.

**Comment by j-kaltes** [comment]
I have made Juggluco work with some Chinese Sibionics sensor and it turned out not to work with other Sibionics sensors. I don't know how exactly these sensors are called.
![inner](https://github.com/user-attachments/assets/2598d395-0d51-4900-8870-2fd9b60c7353)
![innterside](https://github.com/user-attachments/assets/b4f9802f-b781-4543-bd9e-7c0508bb6e6d)
![outer](https://github.com/user-attachments/assets/58ff1915-d090-4c7b-9e67-aee8b9759ebd)
![outerside2](https://github.com/user-attachments/assets/cbfb2210-cfe8-43bd-a76a-5337f694b87f)

**Comment by postn** [comment]
Thanks for the details. By the images on AliExpress this is how the box looks like too. If I indeed get the Chinese version of the CGM can I then use Photo (as I don't see sibionics in the menu) to scan the qr code?

**Comment by j-kaltes** [comment]
You scan the data matrix by making a photo.

**Comment by postn** [comment]
Just an update, the sensor I received is Chinese. My current libre2 ends in a couple of days. Will report back if everything works. Thanks.

**Comment by postn** [comment]
Just to confirm, the app worked well. Thanks again for the amazing app.
